# Generated by Django 3.0.2 on 2021-03-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('topic', models.IntegerField(choices=[(0, 'Politics'), (1, 'Health'), (2, 'Sport'), (3, 'Tech')], default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('message_body', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Expired')], default=0)),
            ],
        ),
    ]
