# Generated by Django 3.0.2 on 2021-03-20 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20210320_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('live', 'Live'), ('expired', 'Expired')], default='draft'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.IntegerField(choices=[('politics', 'Politics'), ('health', 'Health'), ('sport', 'Sport'), ('tech', 'Tech')], default=0),
        ),
    ]
