# Generated by Django 3.0.2 on 2021-03-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20210320_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('politics', 'Politics'), ('health', 'Health'), ('sport', 'Sport'), ('tech', 'Tech')], max_length=20),
        ),
    ]
