# Generated by Django 3.0.2 on 2021-03-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20210320_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='95004', editable=False, max_length=5, unique=True),
        ),
    ]
