# Generated by Django 3.0.2 on 2021-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20210320_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='14956', editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(choices=[('politics', 'Politics'), ('health', 'Health'), ('sport', 'Sport'), ('tech', 'Tech')], to='tweets.Topics'),
        ),
    ]
