# Generated by Django 3.0.2 on 2021-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20210320_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='10851', editable=False, max_length=5, unique=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('politics', 'Politics'), ('health', 'Health'), ('sport', 'Sport'), ('tech', 'Tech')], default='Politics', max_length=100),
        ),
    ]
