# Generated by Django 3.0.2 on 2021-04-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0016_auto_20210406_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='65293', editable=False, max_length=5, unique=True),
        ),
    ]
