# Generated by Django 3.0.2 on 2021-04-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0019_auto_20210406_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='79901', editable=False, max_length=5, unique=True),
        ),
    ]
