# Generated by Django 3.0.2 on 2021-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0021_auto_20210407_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='5574', editable=False, max_length=5, unique=True),
        ),
    ]
