# Generated by Django 3.0.2 on 2021-04-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0022_auto_20210407_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_comments', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tweets.Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='36650', editable=False, max_length=5, unique=True),
        ),
    ]
