# Generated by Django 3.0.2 on 2021-04-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0031_auto_20210410_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='442', editable=False, max_length=5),
        ),
    ]
