# Generated by Django 3.0.2 on 2021-04-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0032_auto_20210411_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='59532', editable=False, max_length=5),
        ),
    ]
