# Generated by Django 3.0.2 on 2021-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0033_auto_20210413_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='9595', editable=False, max_length=5),
        ),
    ]
