# Generated by Django 3.0.2 on 2021-04-14 07:17

from django.db import migrations, models
import django.utils.timezone
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0034_auto_20210414_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[tweets.models.Post.validate_expiration]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='62199', editable=False, max_length=5),
        ),
    ]
