# Generated by Django 3.0.2 on 2021-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0035_auto_20210414_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='upvote',
        ),
        migrations.AddField(
            model_name='likes',
            name='like_or_dislike',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='95006', editable=False, max_length=5),
        ),
    ]
