# Generated by Django 3.0.2 on 2021-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0036_auto_20210415_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ManyToManyField(to='tweets.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='88753', editable=False, max_length=5),
        ),
    ]
