# Generated by Django 3.0.2 on 2021-04-17 11:27

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0037_auto_20210417_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(to='tweets.Likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='18519', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[tweets.models.Post.validate_unique]),
        ),
    ]
