# Generated by Django 3.0.2 on 2021-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0041_auto_20210417_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like_or_dislike',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='65422', editable=False, max_length=5),
        ),
    ]
