# Generated by Django 3.0.2 on 2021-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0042_auto_20210417_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='num_comments',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='75229', editable=False, max_length=5),
        ),
    ]
