# Generated by Django 3.0.2 on 2021-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0048_auto_20210417_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_identifier',
            field=models.CharField(blank=True, default='53834', editable=False, max_length=5),
        ),
    ]
